### ISSUE TITLE
PPA out of date

### ISSUE THREAD

**Issue by GoogleCodeExporter** [themanyone/freespeech-vr#2]
```
The PPA listed in the installation instructions hasn't been updated since 2010, 
and current versions of Ubuntu won't recognize it. Is this still the 
recommended way of installing the software?
```

Original issue reported on code.google.com by `colemanwatts` on 13 Nov 2014 at 9:28

**Comment by themanyone** [comment]
Has anyone found a new PPA with the relevant packages? No Ubuntu here. Will try installing it next week after finals.
