### ISSUE TITLE
Garbled Text Outputs

### ISSUE THREAD

**Issue by zenny** [themanyone/freespeech-vr#3]
Hi,

Tried to run it in Ubuntu Precise (14.04) and the results were garbled.

I read aloud:

> Hello and welcome. This is a test of the free speech voice recognition system, running in Linux. It should work on any operating system that supports pocketsphinx.

The result was:

> Pedal and welcome to justifies the tool is cheap system running head a mess issue are and any already the system that a. this thing to to to

Tried to 'learn', but nothing happens, and also tried with other commands but it does not seem to respond.

Any help?

**Comment by themanyone** [comment]
Ah yes. Pocketsphinx takes two or three different texts prepared with the correct spelling of the same words used "in context" in different ways for it to "learn" speech patterns. I went and had it learn a chapter from my school textbooks prior to writing reports on it, for example.

I could publish my private corpus, but it would probably violate Copyright if it contains excerpts from textbooks, although it might be covered under fair use doctrine.
