### ISSUE TITLE
python3: GLib Error "ladspa-gate-1410-so-gate"

### ISSUE THREAD

**Issue by foobar0112** [themanyone/freespeech-vr#5]
On Arch Linux I get following error running `freespeech.py` (`python3` branch):

```Traceback (most recent call last):
  File "freespeech.py", line 710, in <module>
    app = freespeech()
  File "freespeech.py", line 88, in __init__
    self.init_gst()
  File "freespeech.py", line 280, in init_gst
    self.pipeline = Gst.parse_launch('autoaudiosrc ! ladspa-gate-1410-so-gate threshold=-23.0 decay=2.0 hold=2.0 attack=0.01 ! audioconvert ! audioresample ! pocketsphinx name=asr ! fakesink')
gi.repository.GLib.Error: gst_parse_error: no element "ladspa-gate-1410-so-gate" (1)
```

All dependencies installed and checked. Any idea?

**Comment by themanyone** [comment]
You don't have ladspa-gate. It's part of the ladspa-swh plugins, as per the python3 docs https://github.com/themanyone/freespeech-vr/tree/python3

**Comment by themanyone** [comment]
Gstreamer changed the name from ladspa-gate to ladspa-gate-1410-so-gate. Will check it out and see what else needs updating.

**Comment by themanyone** [comment]
You don't have ladspa-gate-1410-so-gate. It's part of the _ladspa-swh-plugins_ dependency package, as mentioned in the python3 docs at https://github.com/themanyone/freespeech-vr/tree/python3
The dependency might be under another name.  _ladspa-swh-plugins_ is the Fedora package.

**Comment by foobar0112** [comment]
Thanks. Installes `swh-plugins` and it works.
https://www.archlinux.org/packages/community/x86_64/swh-plugins/
